apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sharry-app
  namespace: user4-sharry
  annotations:
    argocd.argoproj.io/sync-wave: "101"
  labels:
    gitops.type: app-of-apps
spec:
  destination:
    namespace: user4-sharry
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/apps/sharry/base/apps
    repoURL: https://github.com/niklasheld/argo-workshop.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
